"""empty message

Revision ID: 36ec467958dc
Revises: 
Create Date: 2021-08-10 13:49:29.905310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36ec467958dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('accountType', sa.Enum('client', 'support worker', name='account_type'), nullable=True),
    sa.Column('firstName', sa.VARCHAR(length=30), nullable=True),
    sa.Column('lastName', sa.VARCHAR(length=30), nullable=True),
    sa.Column('dateOfBirth', sa.Date(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', 'other', name='gender_type'), nullable=True),
    sa.Column('contactNo', sa.VARCHAR(length=15), nullable=True),
    sa.Column('homeAddress', sa.VARCHAR(length=50), nullable=True),
    sa.Column('shortBio', sa.VARCHAR(length=140), nullable=True),
    sa.Column('photo', sa.VARCHAR(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asGuardian', sa.BOOLEAN(), nullable=True),
    sa.Column('guardianFirstName', sa.VARCHAR(length=30), nullable=True),
    sa.Column('guardianLastName', sa.VARCHAR(length=30), nullable=True),
    sa.Column('allergies', sa.VARCHAR(length=50), nullable=True),
    sa.Column('likes', sa.VARCHAR(length=50), nullable=True),
    sa.Column('dislikes', sa.VARCHAR(length=50), nullable=True),
    sa.Column('healthNeeds', sa.VARCHAR(length=50), nullable=True),
    sa.Column('ndisNumber', sa.Integer(), nullable=True),
    sa.Column('ndisPlan', sa.Enum('self managed', 'plan managed', name='ndisPlan'), nullable=True),
    sa.Column('planManager', sa.VARCHAR(length=30), nullable=True),
    sa.Column('invoiceEmail', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('support_workers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('languages', sa.VARCHAR(length=50), nullable=True),
    sa.Column('interests', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), nullable=True),
    sa.Column('clientId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clientId'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('connected_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supportWorkerId', sa.Integer(), nullable=True),
    sa.Column('supportWorkerStatus', sa.Enum('sent', 'accepted', name='supportWorkerStatus'), nullable=True),
    sa.Column('clientId', sa.Integer(), nullable=True),
    sa.Column('clientStatus', sa.Enum('sent', 'accepted', 'declined', name='clientStatus'), nullable=True),
    sa.Column('dateConnected', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['clientId'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['supportWorkerId'], ['support_workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), nullable=True),
    sa.Column('clientId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clientId'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shiftStatus', sa.Enum('requested', 'scheduled', 'pending', 'completed', name='Shift Statuses'), nullable=True),
    sa.Column('workerId', sa.Integer(), nullable=True),
    sa.Column('clientId', sa.Integer(), nullable=True),
    sa.Column('requestedFrom', sa.Enum('client', 'worker', name='requester'), nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('startTime', sa.TIME(), nullable=True),
    sa.Column('endTime', sa.TIME(), nullable=True),
    sa.Column('duration', sa.Interval(), nullable=True),
    sa.Column('frequency', sa.Enum('one-off', 'daily', 'weekly', 'fortnightly', 'monthly', name='frequencies'), nullable=True),
    sa.ForeignKeyConstraint(['clientId'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['workerId'], ['support_workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker', sa.Integer(), nullable=True),
    sa.Column('course', sa.VARCHAR(length=30), nullable=True),
    sa.Column('institution', sa.VARCHAR(length=30), nullable=True),
    sa.Column('startDate', sa.Date(), nullable=True),
    sa.Column('endDate', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['worker'], ['support_workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker', sa.Integer(), nullable=True),
    sa.Column('location', sa.VARCHAR(length=50), nullable=True),
    sa.Column('role', sa.VARCHAR(length=30), nullable=True),
    sa.Column('startDate', sa.Date(), nullable=True),
    sa.Column('endDate', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['worker'], ['support_workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mood', sa.Enum('angry', 'sad', 'moderate', 'happy', 'hyperactive', name='moods'), nullable=True),
    sa.Column('incident', sa.BOOLEAN(), nullable=True),
    sa.Column('incidentReport', sa.Text(), nullable=True),
    sa.Column('sessionReport', sa.Text(), nullable=True),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subs_activities',
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], )
    )
    op.create_table('subs_locations',
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subs_locations')
    op.drop_table('subs_activities')
    op.drop_table('reports')
    op.drop_table('work_history')
    op.drop_table('training')
    op.drop_table('shifts')
    op.drop_table('locations')
    op.drop_table('connected_users')
    op.drop_table('activities')
    op.drop_table('support_workers')
    op.drop_table('clients')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
