version: "3.8"
services:
  # this is service name
  postgres-db:
    container_name: postgres_database_container
    restart: always
    image: postgres:alpine  # lightweight version
    environment:
      - POSTGRES_DB=supportsConnect_database
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password

    ### MOUNT DB INIT FILES INTO CONTAINER
    volumes:
      - "./postgres_db/init:/docker-entrypoint-initdb.d"

    ### NETWORKING
    ports:
      - "5432:5432"

      

 
